version: "3"
services:
  app:
    build: .
    container_name: exp-laravel-app
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    image: mysql:5.7
    container_name: exp-laravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

  nginx:
    image: nginx:latest
    container_name: exp-laravel-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  react:
    build:
      context: /home/abhi/react-admin-panel
    container_name: react-container
    ports:
      - "5173:5173"  # ✅ Vite default port
    volumes:
      - /home/abhi/react-admin-panel:/app
      - /app/node_modules  # Avoid syncing node_modules
    stdin_open: true
    tty: true
    depends_on:
      - app
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  mysql_data:
