apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/abhi/ExpTlaravel"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
