name: Deploy Laravel & React App

on:
  push:
    branches:
      - main  # Change this if your branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD || 'missing-secret' }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME || 'missing-secret' }}" --password-stdin

      - name: Build and Push Laravel App Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: xspl/laravel-app:latest

      - name: Build and Push React App Image
        uses: docker/build-push-action@v3
        with:
          context: /home/abhi/react-admin-panel
          file: /home/abhi/react-admin-panel/Dockerfile
          push: true
          tags: xspl/react-admin-panel:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy on Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY || 'missing-secret' }}
          script: |
            docker login -u "${{ secrets.DOCKER_HUB_USERNAME || 'missing-secret' }}" -p "${{ secrets.DOCKER_HUB_PASSWORD || 'missing-secret' }}"
            
            # Pull latest images
            docker pull xspl/laravel-app:latest
            docker pull xspl/react-admin-panel:latest
            docker pull mysql:5.7
            docker pull nginx:latest

            # Stop and remove existing containers
            cd /path/to/docker-compose-dir
            docker-compose down

            # Start new containers
            docker-compose up -d --force-recreate --remove-orphans
